/** Writes REPORT.md from the run's results plus the reviewed findings in findings.ts. */
import { writeFileSync } from "node:fs";
import { FINDINGS, NOT_COVERED } from "../findings";
import type { Result } from "./harness";

const esc = (s: string) => s.replace(/\|/g, "\\|").replace(/\n/g, " ");

function pct(xs: number[], p: number) {
  if (!xs.length) return 0;
  const s = [...xs].sort((a, b) => a - b);
  return s[Math.min(s.length - 1, Math.ceil((p / 100) * s.length) - 1)];
}

export function writeReport(path: string, meta: Record<string, unknown>, results: Result[]) {
  const pass = results.filter((r) => r.status === "PASS").length;
  const fail = results.length - pass;
  const byKind = (k: string) => results.filter((r) => r.kind === k);
  const kinds = ["flow", "failure", "http", "invariant"];
  const lines: string[] = [];
  const dep = meta.deployment as Record<string, unknown> & { txs: { contract: string; hash: string; gasUsed: string; gasLimit: string }[] };

  lines.push("# Plans Stage A end-to-end report", "");
  lines.push(`Generated by \`npm --prefix e2e/stage-a test\` on ${meta.finished}. Every row below is re-created from scratch on each run (fresh anvil fork, fresh throwaway keys).`, "");
  lines.push("## Result", "");
  lines.push(`**${pass} passed, ${fail} failed** out of ${results.length} scenarios.`, "");
  lines.push("| Kind | Pass | Fail |", "|---|---:|---:|");
  for (const k of kinds) {
    const xs = byKind(k);
    lines.push(`| ${k} | ${xs.filter((r) => r.status === "PASS").length} | ${xs.filter((r) => r.status === "FAIL").length} |`);
  }
  lines.push("");

  lines.push("## Environment", "");
  lines.push(`- Chain: local \`anvil\` fork of Monad mainnet (chain id 143) from \`${meta.forkUrl}\` at block ${meta.forkBlock}, \`--code-size-limit 131072\`. Real AUSD \`${dep.ausd}\`; actors funded by writing AUSD's ERC-7201 balance slots.`);
  lines.push(`- Contracts deployed through the canonical CREATE2 deployer with \`Deploy.s.sol\`'s salts (same addresses as a real deployment of this bytecode): PlansFactory \`${dep.plansFactory}\`, ClaimEscrow \`${dep.claimEscrow}\`, Pot implementation \`${dep.potImplementation}\`, KeyRegistry \`${dep.keyRegistry}\`, PlansSend \`${dep.plansSend}\`.`);
  for (const t of dep.txs) lines.push(`  - ${t.contract}: ${t.hash} (gas used ${t.gasUsed}, limit ${t.gasLimit} = anvil eth_estimateGas + 10 %)`);
  lines.push("- Relayer: `relayer/dist` (`pnpm build`), `CHAIN_ID=143`, RPC and WS on the fork, 3 throwaway lanes, demo on (throwaway Ben/Asha/Maya keys), faucet/push/long-stop off, FX source = a local mock of frankfurter.app. Every gas limit came from the relayer's own `MonadGasEstimator` (eth_estimateGas on the fork).");
  lines.push("- A second relayer with the production defaults for body size and rate limits (64 KB, 120 POST/min/IP, 30 relays/min/account, 30 createPot/day/IP) for the limit tests.");
  lines.push(`- \`eth_sendRawTransactionSync\` on anvil: ${meta.relayerSync === true ? "supported (sync sends)" : "not supported (relayer fell back to eth_sendRawTransaction + receipt polling)"}.`, "");

  // latency
  const lat = results.flatMap((r) => r.latency);
  const byAction = new Map<string, typeof lat>();
  for (const l of lat) byAction.set(l.action, [...(byAction.get(l.action) ?? []), l]);
  lines.push("## Relayer latency on the fork", "");
  lines.push("`latencyMs` = signed tx handed to the RPC until the receipt; `totalMs` = HTTP request in until the receipt (validation, eth_call, eth_estimateGas, send); `client` = measured by the harness around the HTTP call. Anvil automines, so these measure the relayer's own overhead, not Monad block times.", "");
  lines.push("| Action | n | latencyMs p50 / p95 / max | totalMs p50 / p95 / max | client ms p50 / p95 | gasUsed / gasLimit (median) |", "|---|---:|---|---|---|---|");
  for (const [action, xs] of [...byAction.entries()].sort()) {
    const l = xs.filter((x) => x.latencyMs !== undefined).map((x) => x.latencyMs!);
    const t = xs.filter((x) => x.totalMs !== undefined).map((x) => x.totalMs!);
    const c = xs.map((x) => x.clientMs);
    const gu = xs.filter((x) => x.gasUsed).map((x) => Number(x.gasUsed));
    const gl = xs.filter((x) => x.gasLimit).map((x) => Number(x.gasLimit));
    const tri = (v: number[]) => (v.length ? `${pct(v, 50)} / ${pct(v, 95)} / ${Math.max(...v)}` : "-");
    lines.push(`| ${action} | ${xs.length} | ${tri(l)} | ${tri(t)} | ${pct(c, 50)} / ${pct(c, 95)} | ${gu.length ? `${pct(gu, 50)} / ${pct(gl, 50)}` : "-"} |`);
  }
  const all = lat.filter((x) => x.totalMs !== undefined).map((x) => x.totalMs!);
  const sub = lat.filter((x) => x.latencyMs !== undefined).map((x) => x.latencyMs!);
  lines.push("", `All ${lat.length} relayed transactions: latencyMs (submit -> receipt) p50 ${pct(sub, 50)}, p95 ${pct(sub, 95)}, max ${Math.max(...sub)}; totalMs p50 ${pct(all, 50)}, p95 ${pct(all, 95)}, max ${Math.max(...all)}.`);
  lines.push("", "Outliers in totalMs are most likely anvil fetching cold state from the forked RPC during the relayer's eth_call/eth_estimateGas (for example, settling the 50-member pot first reads ~100 untouched AUSD balance and allowance slots from rpc.monad.xyz). They are not relayer processing time. `demo createPot` is sent by the demo service, whose response carries only latencyMs.", "");

  // findings
  lines.push("## Findings", "");
  if (!FINDINGS.length) lines.push("None.", "");
  for (const f of FINDINGS) {
    lines.push(`### ${f.id}. ${f.title}`, "");
    lines.push(`- **Where:** ${f.where}`, `- **Severity:** ${f.severity}`, `- **Scenario:** ${f.scenario}`, "");
    lines.push(f.body.trim(), "");
  }
  const failing = results.filter((r) => r.status === "FAIL");
  if (failing.length) {
    lines.push("### Failing scenarios in this run", "");
    for (const r of failing) lines.push(`- #${r.id} [${r.group}] ${r.name}: ${esc(r.error ?? "")}`);
    lines.push("");
  }

  // table
  lines.push("## Scenarios", "");
  lines.push("Failure rows also assert that no transaction reached the target and that a fingerprint of every pot (balance, nets, counters, flags), the escrow and all tracked AUSD balances is unchanged. Invariant rows check I1 (Σ netOf = pot balance) for every pot, escrow balance = Σ open claims, PlansSend holds 0, AUSD conserved across all tracked addresses, AUSD totalSupply unchanged, and a pot holding 0 after a clean settle.", "");
  lines.push("| # | Group | Scenario | Kind | Result | Expected | Actual | Tx hashes (fork) | Latency ms (tx / total / client) |", "|---:|---|---|---|---|---|---|---|---|");
  for (const r of results) {
    const txs = r.txs.length ? r.txs.join("<br>") : "-";
    const l = r.latency.length ? r.latency.map((x) => `${x.latencyMs ?? "-"} / ${x.totalMs ?? "-"} / ${x.clientMs}`).join("<br>") : "-";
    const actual = r.status === "FAIL" ? `**${esc(r.error ?? r.actual)}**` : esc(r.actual);
    const notes = r.notes.length ? `<br>_${esc(r.notes.join(" "))}_` : "";
    lines.push(`| ${r.id} | ${esc(r.group)} | ${esc(r.name)} | ${r.kind} | ${r.status} | ${esc(r.expected)} | ${actual}${notes} | ${txs} | ${l} |`);
  }
  lines.push("");
  lines.push("## Not covered", "");
  for (const n of NOT_COVERED) lines.push(`- ${n}`);
  lines.push("");
  writeFileSync(path, lines.join("\n"));
}
