// Fills the Monad MAINNET indexer configs from contracts/deployments/143.json (written by
// contracts/script/monad-send.mjs after the mainnet deploy):
//   config.mainnet.yaml          Envio Cloud (HyperSync), addresses + start block filled in
//   config.selfhost.mainnet.yaml the same, reading Monad mainnet over its public RPCs (self-hosted on
//                                Railway: set ENVIO_CONFIG=config.selfhost.mainnet.yaml)
//
//   node indexer/scripts/mainnet-config.mjs                    (from the repo root)
//   node indexer/scripts/mainnet-config.mjs --deployments <file> --check
//
// start_block = the earliest block among the transactions in 143.json that created the CURRENT
// addresses (KeyRegistry is deployed first). --check prints what would change and writes nothing.
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const INDEXER = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const REPO = path.resolve(INDEXER, "..");
const args = process.argv.slice(2);
const opt = (k) => {
  const i = args.indexOf(`--${k}`);
  return i >= 0 ? args[i + 1] : undefined;
};
const depFile = opt("deployments") ?? path.join(REPO, "contracts", "deployments", "143.json");
const checkOnly = args.includes("--check");
const outDir = opt("out-dir") ?? INDEXER;

if (!existsSync(depFile)) throw new Error(`no ${depFile}: deploy mainnet first (docs/mainnet-launch.md)`);
const d = JSON.parse(readFileSync(depFile, "utf8"));
if (Number(d.chainId) !== 143) throw new Error(`${depFile} is chain ${d.chainId}, not 143`);
const isAddr = (a) => /^0x[0-9a-fA-F]{40}$/.test(a ?? "");
const fields = { PlansFactory: d.plansFactory, KeyRegistry: d.keyRegistry, ClaimEscrow: d.claimEscrow, PlansSend: d.plansSend, FxReference: d.fxReference };
for (const [k, v] of Object.entries(fields)) if (!isAddr(v)) throw new Error(`${depFile}: ${k} address missing`);
const current = new Set([d.keyRegistry, d.fxReference, d.plansSend, d.plansFactory].map((a) => a.toLowerCase()));
const blocks = (d.transactions ?? []).filter((t) => current.has(String(t.address).toLowerCase()) && Number(t.blockNumber) > 0).map((t) => Number(t.blockNumber));
if (!blocks.length) throw new Error(`${depFile}: no transaction for the current addresses, so no start block`);
const startBlock = Math.min(...blocks);

const src = readFileSync(path.join(INDEXER, "config.mainnet.yaml"), "utf8");
const head = src.slice(0, src.indexOf("\nchains:\n") + 1);
if (!head) throw new Error("config.mainnet.yaml has no chains: section; update this script");
const contractsYaml = (indent) =>
  ["PlansFactory", "Pot", "KeyRegistry", "ClaimEscrow", "PlansSend", "FxReference"]
    .map((n) => (n === "Pot" ? `${indent}- name: Pot` : `${indent}- name: ${n}\n${indent}  address: "${fields[n]}"`))
    .join("\n");
const cloud = `${head}chains:
  # Monad mainnet (HyperSync: https://143.hypersync.xyz). Filled from contracts/deployments/143.json by
  # indexer/scripts/mainnet-config.mjs; start_block is the deployment block.
  - id: 143
    start_block: ${startBlock}
    contracts:
${contractsYaml("      ")}
`;
const selfhost = cloud
  .replace(
    "# Monad MAINNET indexer config (deploy as a separate Envio indexer with config file config.mainnet.yaml).",
    "# config.selfhost.mainnet.yaml: the MAINNET indexer for SELF-HOSTING (Railway, ENVIO_CONFIG=config.selfhost.mainnet.yaml),\n# generated by scripts/mainnet-config.mjs from config.mainnet.yaml. Reads Monad mainnet over public RPC (no HyperSync token).\n# Do not edit by hand.",
  )
  .replace(
    `    start_block: ${startBlock}\n`,
    `    start_block: ${startBlock}
    # Self-hosted: Monad's public RPCs (eth_getLogs is capped at 100 blocks there).
    rpc:
      - url: https://rpc.monad.xyz
        for: sync
        initial_block_interval: 100
        interval_ceiling: 100
        backoff_millis: 1000
      - url: https://rpc1.monad.xyz
        for: fallback
        initial_block_interval: 100
        interval_ceiling: 100
`,
  );
if (!selfhost.includes("for: sync") || !selfhost.includes("SELF-HOSTING")) throw new Error("config.mainnet.yaml layout changed; update scripts/mainnet-config.mjs");

console.log(`mainnet indexer config from ${path.relative(REPO, depFile) || depFile}: start_block ${startBlock}`);
for (const [k, v] of Object.entries(fields)) console.log(`  ${k.padEnd(13)} ${v}`);
if (checkOnly) {
  console.log("--check: nothing written");
} else {
  writeFileSync(path.join(outDir, "config.mainnet.yaml"), cloud);
  writeFileSync(path.join(outDir, "config.selfhost.mainnet.yaml"), selfhost);
  console.log(`wrote ${path.join(outDir, "config.mainnet.yaml")} and config.selfhost.mainnet.yaml`);
}
