import type { MetadataRoute } from "next";

// Icons come from brand/web (generated by brand/scripts/build.mjs). Do not edit them here.
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: "Plans",
    short_name: "Plans",
    description: "A group money pot for trips and plans.",
    start_url: "/",
    display: "standalone",
    background_color: "#0C1511",
    theme_color: "#10231B",
    icons: [
      { src: "/icons/icon-192.png", sizes: "192x192", type: "image/png" },
      { src: "/icons/icon-512.png", sizes: "512x512", type: "image/png" },
      { src: "/icons/icon-maskable-512.png", sizes: "512x512", type: "image/png", purpose: "maskable" },
    ],
  };
}
